salesforce/design-system-react

examples/combobox/readonly-multiple.jsx
examples/combobox/readonly-single.jsx

Current examples use "placeholder" to no effect. Examples should use "placeholderReadOnly".

fix(combobox): Fix example to use placeholderReadOnly

---

examples/tree/default.jsx
examples/tree/stories.jsx

Current tree example uses `forceUpdate` which is a bad practice.  This only updates the examples.

Tree example: Remove forceUpdate

---

examples/lookup/stories.jsx

The lookup still looks a bit off, but from my understanding this is now deprecated? Either way thought we should still make sure the storybook for it at least loads.

Fix story Lookup standard w/ accounts not loading

---

components/data-table/column-check-props.js
components/data-table/column.jsx
components/data-table/private/header-cell.jsx
examples/data-table/advanced.jsx
tests/data-table/__snapshots__/data-table.snapshot-test.jsx.snap
tests/data-table/data-table.browser-test.jsx
utilities/warning/if-one-then-both-required-property.js

Fixes: #1162
- Default column sort has been ascending since February, this changes it back to null which allows for initial order to be unsorted, but show an ascending arrow on mouse hover.
- isSorted is added to the public props
- sortDirection is required if isSorted is truthy (this should error out if you aren't using both props now)
- if isSorted switches to false, then column sort state gets reset, this allows the arrow on the previously sorted column to revert to ascending.
I'd love to remove state out of here, but that'd be a breaking change. Currently this should behave as it has (that is incorrectly) without change UNLESS `isSorted` and `sortDirection` is used which is the recommended solution
The new UX pattern is that all sortable, unsorted columns should:
* become ascending …

Initial state of DataTable sort is null, unless prop is passed

---

components/progress-indicator/private/step.jsx
tests/progress-indicator/progress-indicator.browser-test.jsx

Tooltip triggers should be triggered by focusable elements not an `li`. Fixes #1160.
@jjangsfdc

Progress Indicator: Move tooltip to button trigger

---

.editorconfig
README.md
components/icon-settings/index.jsx
components/utilities/utility-icon/check-props.js
components/utilities/utility-icon/index.jsx
examples/component-docs.json
examples/icon-settings/iconPath.jsx
examples/icon-settings/sprite.jsx
examples/icon-settings/stories.jsx
examples/index.js
examples/stories.js
package.json
tests/accordion/__snapshots__/accordion.snapshot-test.jsx.snap
tests/alert/__snapshots__/alert.snapshot-test.jsx.snap
tests/button-group/__snapshots__/button-group.snapshot-test.jsx.snap
tests/combobox/__snapshots__/combobox.snapshot-test.jsx.snap
tests/filter/__snapshots__/filter.snapshot-test.jsx.snap
tests/panel/__snapshots__/filtering.snapshot-test.jsx.snap
tests/toast/__snapshots__/toast.snapshot-test.jsx.snap
utilities/constants.js

When using webpack it's a pain to use the icons. You need to either manually copy the sprites or use a copy loader. 
Allowing the sprites to be assigned in the icon settings means webpack can re-write the urls and you don't need to co-ordinate a copy and path assignment.
```javascript
import utilitySprite from '@salesforce-ux/design-system/assets/icons/utility-sprite/svg/symbols.svg';
import customSprite from '@salesforce-ux/design-system/assets/icons/custom-sprite/svg/symbols.svg';
() => (
<IconSettings utilitySprite={utilitySprite} customSprite={customSprite}>
</IconSettings>
)
```

Make icons settings webpack friendly

---

components/utilities/highlighter/index.jsx

Fixes issue #1193 
This adds the title attribute for anything that uses `components/utilities/highlighter`. react-highlighter passes along any additional props so this will work for the Search enabled tree as well.
---

add "title" attribute to string nodes (span)

---

components/button/index.jsx

Fixes issue #1202 
Removing the `active` property from state . since it is not being used. 
---

#1202 - Removed setState call when handling click to set active property

---

package.json

- Runs prettier, then eslint fix on staged files before commit, makes eslint error out on commit if warnings exist after lint fix is run.
- Run json and markdown files through prettier, too, on commit.

Run lint fix on commit

---

components/navigation/private/item.jsx
components/tree/private/branch.jsx
components/tree/private/item.jsx

Fixed `Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named "defaultProps" instead`

Fix getDefaultProps warning in Tree

---

tests/README.md

Explains benefits of #1241 in tests readme.
@cormacmccarthy Builds upon your original snapshot PR and moves Storyshot testing to the top in order to promote its use and automatic test creation feature.

Update tests readme with StoryShots features

---

components/icon-settings/index.jsx

It can only be one node
Fixes issue #1239.

Document child nodes of IconSettings

---

components/modal/index.jsx

Add clarity that they are not just buttons, but typically are.
Fixes issue #1286

Update Modal footer prop description

---

scripts/dist.sh
scripts/publish-to-git.js

This was proposed in August 2017 to be done in October 2017. v0.8.8 will be the last AMD release. This PR removes the RequireJS module tag.
Fixes #1289
To test `npm run publish:origin` and check your forked origin repo. It worked for me.

Remove build/publish process for AMD tag

---

package.json

Fixes https://github.com/salesforce/design-system-react/issues/1296
Allows SLDS v2.6.0-alpha in our allowable range.
---

Update SLDS peer dependency to allow 2.6.0-alphas

---

components/menu-dropdown/menu-dropdown.jsx

Update menu children description to scare folks away from using it. Since most menu experiences can be done with options and listItemRenderer. Non-menu experiences should probably use Popover with a listbox that has tab index and not the MenuDropdown/Children API.

Update Dropdown Menu children description

---

package.json

Fixes #1302
new url points to the /input folder instead of broken /input/inline.
---

fixes broken link to source of Inline Edit Inputs in docs

---

components/combobox/combobox.jsx
components/date-picker/date-picker.jsx
components/menu-dropdown/menu-dropdown.jsx
components/popover/popover.jsx
components/tooltip/index.jsx
components/utilities/dialog/index.jsx

This sets `flip.enabled` based on the `hasStaticAlignment` prop.
Fixes https://github.com/salesforce/design-system-react/issues/1312
@interactivellama could you take a look?  Thanks!
---

Set flip.enabled based on hasStaticAlignment prop

---

components/component-docs.json
components/slider/__tests__/slider.browser-test.jsx
components/slider/index.jsx

`onChange` and `onInput` now pass in `event, { value: [string] }`. This is a type change from @DanFerro great addition to the library. I've talked with him, and we agreed that it should be a `string`. This is not a breaking change, since the Slider was never released in a version.
Build docs is also run with updated prop comments.
---

Slider: Use string in event callback

---

components/index.js

I do know that lookup is currently deprecated, but we still use it and I've spent a full day trying to migrate one lookup to a combobox.
In the meantime this DefaultSectionDivider used to be exposed in es6 modules, but not in commonjs. It'd be a whole world easier if we just exposed it in both until the lookup component is actually killed. Refactoring is not part of the scope of upgrading DSR for me.

Allow importing lookup DefaultSectionDivider

---

components/data-table/__tests__/__snapshots__/data-table.snapshot-test.jsx.snap
components/data-table/private/header-cell.jsx

Fixes #1328
focusable attribute on the `th` of `header-cell.js` must be a boolean, cannot be null
---

Fix bug with sortable causing focusable attribute to throw an error

---

components/combobox/__tests__/combobox.browser-test.jsx
components/combobox/combobox.jsx

Fixes #1338 
I found an issue in combobox.jsx where the passed-in onOpen callback is never triggered in handleOpen function.
Added a test for this change as well. Note that more component tests can be added to test the event trigger, but maybe not in this PR.
FYI - The three test failures below are not related to this PR, they occur without the changes.

Trigger onOpen callback in Combobox

---

components/app-launcher/__tests__/tile.browser-test.jsx
components/app-launcher/tile.jsx
components/progress-indicator/__tests__/progress-indicator.browser-test.jsx
components/progress-indicator/private/step.jsx
components/slider/__tests__/slider.browser-test.jsx
components/tooltip/__docs__/site-stories.js
components/tooltip/__docs__/storybook-stories.jsx
components/tooltip/__examples__/learn-more.jsx
components/tooltip/__tests__/tooltip.browser-test.jsx
components/tooltip/check-props.js
components/tooltip/index.jsx
utilities/__tests__/warnings.browser-test.jsx
utilities/warning/deprecated-property-value.js

Fixes #961
and #1228
* The assistive text isn't needed anymore. It works fine now that PopperJS is used as is--it reads the text twice in VoiceOver--Adam approves.
* Learn more variant is added.
* warning and error are moved to theme in a backwards compatible way. This will be removed in a breaking changing in the future.
---

Learn more tooltip

---

components/combobox/__tests__/combobox.browser-test.jsx

Replacement for #1187 with updated master branch pull down 
Fixes #1340
This limits input focus to not just when `onRequestFocus` is made, but limits the focus call to just the change in internal menu open state or prop `isOpen`. This is helpful for when Datepicker menu is a controlled with prop `isOpen`.
---

Focus input if menu was actually open and not just requested to close

---

components/data-table/row-actions.jsx

Still have no idea what a hint is. Couldn't really find anything about hints at https://www.lightningdesignsystem.com/components/buttons/#hint as specified across multiple locations in docs and code. Is this a deprecated thing?
Either way it's messing with the styling of the dropdown icon for me, and there's no way to override it.

Make hint an optional field for data table actions

---

components/tree/__tests__/tree.browser-test.jsx
components/tree/index.jsx
components/tree/private/branch.jsx
components/tree/private/item.jsx
package.json

This includes accessibility changes for the Tree component.
- Add role=”presentation” to buttons and anchors
- Add keyboard navigation: up/down to navigate, left/right to open/close
- Add aria-label=”{the label for that node}”
@interactivellama I'd like to get initial impressions on this approach.  Can you let me know what you think?
Fixes https://github.com/salesforce/design-system-react/issues/609
---

Tree keyboard navigation

---

.travis.yml
components/component-docs.json

Replaces `npm install` with `npm ci`. The main difference is that `package.json`'s versions are ignored and `package-lock.json` is used.
I'm not 100% sure folks know to update `package-lock.json`.
---

Use npm ci for travis ci

---

package-lock.json
package.json
scripts/inline-icons.js

So this is related to (but not the final fix for) #1366 . Typically Windows users will not have python and a g++ compiler tool chain installed in order to compile native addons. A lot of modules work-around this issue by offering pre-compiled addons (like node-sass), but `node-expat` (a dependency of `xml2json`) does not.
Since this is just in some tooling and I was able to use the popular `xml2js` to fill in with the same functionality, I thought this may be another way to help improve the Windows contributor experience.

Switch xml2json to xml2js in tooling

---

components/component-docs.json
components/tree/__docs__/storybook-stories.jsx
components/tree/__examples__/default.jsx
components/tree/__tests__/tree.browser-test.jsx
components/tree/index.jsx
components/tree/private/branch.jsx
components/tree/private/item.jsx
utilities/sample-data/tree/index.jsx
utilities/sample-data/tree/sample-nodes-with-initial-state.jsx

This fixes two Tree bugs: 
- Tree is not rendered on props changes https://github.com/salesforce/design-system-react/issues/1377
- Show proper aria-label value when label is a node https://github.com/salesforce/design-system-react/issues/1378
---

Tree bug fixes introduced by keyboard navigation

---

components/button-group/__examples__/icon-group.jsx
components/button-group/__tests__/__snapshots__/button-group.snapshot-test.jsx.snap

- Aligning button group example with SLDS example, that is, changing icons and assistive text.
Button group will now look like this:
Fixes #1229 
---

Align button group example with SLDS example

---

components/app-launcher/__docs__/storybook-stories.jsx
components/app-launcher/__tests__/app-launcher.browser-test.jsx
components/app-launcher/check-props.js
components/app-launcher/index.jsx
components/component-docs.json
components/modal/__docs__/storybook-stories.jsx
components/modal/__tests__/modal.browser-test.jsx
components/modal/check-props.js
components/modal/index.jsx
components/popover/__docs__/storybook-stories.jsx
components/popover/__tests__/popover.browser-test.jsx
components/popover/check-props.js
components/popover/popover.jsx

This PR consolidate assistive text props under one `assistiveText` prop for the following components:
- App Launcher
- Popover
- Modal
More components to come!
---

Consolidate assistiveText props under one object [App Launcher, Popover, Modal]

---

components/modal/index.jsx

- Removing static positioning on modal overlay.
- Adding z-index to modal overlay as per SLDS guidelines.
This should fix the modal jump issue that consumers are experiencing, including `design-system-react-site` consumer - manually tested in repo.
This should also not regress [#200](https://github.com/salesforce/design-system-react/issues/200) - also manually tested.
Fixes #963 
---

Fixing issue where modal jumps when opened

---

components/utilities/dialog/index.jsx

overflowBoundaryElement Dropdown with align=right uses max-width instead of inherited children width

---

docs/codebase-overview.md

Replaces "Child component decorator pattern" as the preferred composition pattern and best practice of this library. Please review for clarity, since this is so abstract.
This explains why https://github.com/salesforce/design-system-react/pull/1413 does what it does. I'm open to a better name for this pattern, too!

Document component composition with prop spread

---

components/data-table/__examples__/advanced.jsx
components/data-table/__tests__/data-table.browser-test.jsx
components/data-table/row-actions.jsx

Fixes https://github.com/salesforce/design-system-react/issues/1403
Added dropdown option to DataTableRowActions that takes MenuDropdown component as a property to allow support for all dropdown properties by overriding defaults
---

Added dropdown option to DataTableRowActions

---

components/tree/private/branch.jsx

Fixes #1427 
Fixing JS errors on tree accessibility.
---

Fixing JS errors in tree accessibility

---

components/utilities/utility-icon/index.jsx

We are seeing a problem when we try to update an `Icon` component. 
Our code looks like below, where the `name` and `category` are dyanmic and update frequently. After the initial render, we update these and are not seeing the SVG icon update. We have seen that url used in the `svg > use` is updated, but the icon disappears. 
Adding a `key` attribute to this SVG element seems to re-render the icon correctly, but we do get a bit of a flash.
```js
const Test = ({ name, category }) => (
<div className="slds-box--border">
<Icon
category={category}
name={name}
style={iconStyles}
/>
</div>
);
```
**Not working**
https://drive.google.com/open?id=10NjYbVF3foqqx-puufXsKdVaVzCHPA8s
**Working**
https://drive.google.com/open?id=1uK5EoZb-K-LiCpSN70daLgfXbnhTYrLZ
---

add key to svg icon (re-render icon when changes are made)

---

utilities/warning/url-exists.js

Fixes #1423 
When checking to see if an icon exists, url-exists is using the standard xmlHttpRequest, which is synchronous, and is deprecated.  I added a check to see if `fetch` is available to the browser, in which case it will use fetch, which is async and standard in modern browsers.

Use Fetch for url-exists, if available

---

docs/create-react-app.md

Removes web inspector warnings for missing fonts when using with create-react-app.
---

Document copying over SLDS fonts to public

---

components/date-picker/__tests__/__snapshots__/datepicker.snapshot-test.jsx.snap
components/date-picker/private/year-picklist.jsx

Fix for the Datepicker component where the year list did not show the full year in Firefox and IE.
---

Fix Datepicker Year Picklist Display Issue

---

components/app-launcher/index.jsx
components/component-docs.json
components/modal/index.jsx
utilities/warning/check-app-element-set.js

- Adds warning to Modal component to let consumer know when `Settings.setAppElement(el)` was not set prior to using this component.
- Adds prop `ariaHideApp` on `Modal` and `App Laucher` component as a way to opt-out of having to set `Settings.setAppElement(el)`.
Fixes #780 
---

Add warning when Settings.setAppElement is not set.

---

.travis.yml

Due to TravisCI issues that occur about once a week:
```
0.49s$ npm ci
npm ERR! Unexpected string in JSON at position 609390
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-07-25T19_59_42_628Z-debug.log
The command "npm ci" failed and exited with 1 during .
```
---

Revert to npm install from npm ci

---

preset/package.json.txt

Add txt file copy of package.json so that new preset versions did not have to be created from scatch.
Non-production code.
---

Add preset package.json

---

components/component-docs.json
components/site-stories.js
components/spinner/__examples__/default.jsx
components/spinner/index.jsx
package.json

Add Spinner to doc site

---

components/component-docs.json
components/menu-dropdown/menu-dropdown.jsx

Fixes #799
Surfaces and documents default of menu height of 5
---

Dropdown: Document that default menu height is 5

---

components/modal/trigger.jsx

Fixes #1394
Add the following to any Storybook example to see output.
```
import ModalTrigger from '~/components/modal/trigger';
ModalTrigger.open({ content: '', footer: ' ' });
```
---

Deprecate this one little weird Modal Trigger trick your grandmother knew about

---

components/global-header/button.jsx
components/global-header/private/dropdown-trigger.jsx

Fixes #1318 
When `GlobalHeaderButton` is used on its own, it is appropriately wrapped in an `<li>`. This PR makes it so that when it's called from within `GlobalHeaderTrigger` (which adds its own wrapping `<li>`, it is not double-wrapped.
---

Hotfix GlobalHeaderButton invalid markup when used within GlobalHeaderTrigger

---

components/bread-crumb/index.jsx
components/forms/input/index.jsx
components/forms/radio/index.jsx
components/forms/textarea/index.jsx
components/navigation/index.jsx
components/popover-tooltip/index.jsx
utilities/warning/component-has-moved.js

Fixes #1418
This tells folks when their import paths are pointing to an old alias.
---

Moved components warning

---

components/tree/index.jsx

This allows icons and formatting with spans if it is needed. Both are outside the SLDS spec, but should be allowed with designer direction. This is already present in item and branch sub components, but was overlooked when added to Tree's top level propTypes

Tree: Allow label to be a React node

---

components/date-picker/__tests__/__snapshots__/datepicker.snapshot-test.jsx.snap
components/date-picker/private/navigation.jsx
components/date-picker/private/year-picklist.jsx

- Fix menu items not showing up correctly
- Fix console warning showing up when selecting menu item
- Set slds-datepicker class on menu item to set correct font size of date picker
Fixes #1504 
---

SLDSDatePicker bug fix: Fixing issue where year picker doesn't show years correctly

---

components/input/check-props.js

There is an incorrect warning when rendering an `Input`:
`Warning: [Design System React] Only one of the following props is needed by SLDSInput: [assistiveText,label].`
This is caused by this change: https://github.com/salesforce/design-system-react/pull/1491/files#diff-18c5980c2c017c14bdf52f5ee38d0680R39. We should be checking `assistiveText.label` and not `assistiveText`.
After this fix, the warning looks like: `Warning: [Design System React] Only one of the following props is needed by SLDSInput: [assistiveText.label,label].`.
Fixes https://github.com/salesforce/design-system-react/issues/1510.
---

Fix incorrect warning in Input

---

components/app-launcher/tile.jsx
components/button/index.jsx
components/menu-picklist/__examples__/tooltip-list-item.jsx
components/page-header/__docs__/storybook-stories.jsx
components/page-header/private/detail-block.jsx
components/tooltip/__docs__/storybook-stories.jsx
components/tooltip/__examples__/base.jsx
components/tooltip/__examples__/button-group.jsx
components/tooltip/__examples__/button.jsx
components/tooltip/__tests__/tooltip.browser-test.jsx

Prevent warnings when importing components like `Button` and `PageHeader` or their dependents.
Also update examples to import Tooltip instead of moved PopoverTooltip.
Fixes #1514 
---

Use Tooltip instead of PopoverTooltip internally

---

components/icon-settings/__docs__/site-stories.js
components/icon-settings/__docs__/storybook-stories.jsx
components/icon-settings/__examples__/on-request-icon-path.jsx
components/icon-settings/index.jsx
components/utilities/utility-icon/check-props.js
components/utilities/utility-icon/index.jsx

…paths.
The motivation for this change is tied to Quip's Live Apps platform where we cannot serve
sprite sheets on the same domain as our iframe, thus breaking the ability to load XML-like
data (the SVG sprite sheets) due to browser security restrictions arounds same domain+port.
Fixes #1408
---

Adds `onRequestIconPath` to IconSettings

---

components/alert/__docs__/storybook-stories.jsx
components/alert/__examples__/custom-style.jsx
components/alert/__tests__/alert.browser-test.jsx
components/alert/index.jsx
components/component-docs.json

Prop style for alert

---

components/component-docs.json
components/toast/__docs__/storybook-stories.jsx
components/toast/__examples__/custom-style.jsx
components/toast/__tests__/toast.browser-test.jsx
components/toast/index.jsx

Toast new prop style

---

components/utilities/dialog/index.jsx
components/utilities/dialog/portal.jsx
utilities/dom-element-focus.js

Fixes #1566
This removes the scrolling affect on focus for popovers in portals and adds styling to the portal element in order to ensure it is hidden and adds a class to make it targetable with styles.
The easiest way to test this is to add
```
<div style={{ height: '1000px' }} />
```
to a storybook example of a `Filter`
focus's `preventScroll: true` is fairly [new](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus). 
I'm hesitant to add an additional tests that looks at scrolling and focus events within the test suite, but I'm open to suggestions on how to prevent regressions.
---

Prevent scroll on focus in portal popovers

---

components/component-docs.json
components/input/__tests__/input.browser-test.jsx
components/input/index.jsx

Makes the increment/decrement buttons disabled if the value is outside the allowed range and fixes an endless increment/decrement bug
Fixes #1644 
---

Disable increment/decrement when min/max is hit

---

components/tree/private/item.jsx
components/tree/private/render-branch.jsx

If a tree has a complex object for its nodes (deeply nested, etc), the keyboard select fails to work properly. This is due to the complex objects being compared by reference, instead of by value. To fix this, we are now finding the node by id, since that is a required value for every node.
---

Tree: Compare cached flattened nodes with id key

---

components/input/private/inner-input.jsx

Matches type defined in https://github.com/salesforce/design-system-react/blob/master/components/input/index.jsx#L173.

Input inlineHelpText can be `node` as well as `string`.

---

components/button/index.jsx
components/date-picker/__tests__/__snapshots__/datepicker.snapshot-test.jsx.snap
components/split-view/__tests__/__snapshots__/split-view.snapshot-test.jsx.snap
components/tooltip/__docs__/storybook-stories.jsx
components/tooltip/__examples__/base.jsx
components/tooltip/index.jsx
utilities/get-aria-props.js

Fixes #1549 
Fixes #1705
* If `learnMore` Tooltip variant is used without onClickTrigger, then the “no click” basic info icon tooltip will be used with a “disabled” button as trigger.
* If onClickTrigger is defined, a link will be rendered (this is the current behavior for learn more tooltips)
---

Tooltip: Require onClickTrigger for learn more pattern 

---

components/menu-dropdown/menu-dropdown.jsx
components/utilities/menu-list/index.jsx

Fixes #
As a consumer of DSR, currently when passing a number type length to MenuDropdown, I get a propType validation error. I am currently striving for 0 validation errors, but think that number type should be supported by the length prop. I should not have to know about internal implementation details that it gets cast to a string (which is a clean cast) for the class name.
---

Menu dropdown propType should support numbers for length

---

.eslintrc.js
components/utilities/dialog/index.jsx

Fixes #1744
Instead of only inheriting `iconAssets`, inherit all `IconSettings` related context properties based on `IconSettings.childContextTypes`.
---

Fix inheritance of IconSettings context for overflowBoundaryElement Dialog. Add ESLINT skipBlankLines/skipComments max lines rule

---

docs/release.md

This will prevent a "waterfall dependency" on the maintainers to release while a contributor is waiting for a code merge or library release.
Fixes #1756

Add how to release a tag on a fork

---

CONTRIBUTING.md

I was going through the contributing guideline, as I was planning to implement the progress bar component from LDS.
Fixes #
*  Markdown hyperlink syntax error in the part where it mentions `Create dev storybook stories`, there was a missing ```[```, which I have added.
*  Path of ```constants.js``` is mentioned to be ```/components/constants.js``` but actually is in ```/utitlites/constants.js```

Correct Few Typos in Contributor's Guidelines

---

components/input/__examples__/error.jsx
tests/__snapshots__/story-based-tests.snapshot-test.js.snap

fixed error icon from warning icon to error icon

---

README.md

Fixes #
* In setting up section in the `README.md`  file, `npm install` command was run in the same directory whereas it is required to open the cloned directory for which I have added the `cd design-system-react` command

Update README.md to run install command in right directory while setting up the code base locally

---

components/forms/private/label.jsx

Fixes #1807 
---
There was an warning being thrown when trying to pass a non-string labels.label into combobox. The non-string label was being passed directly into `forms/private/label`. This PR fixes this by making the `label` prop in `forms/private/label` also accept `React.node` without issue.
@interactivellama 

Input: Add node to proptypes in forms/private/label

---

components/data-table/__examples__/advanced-single-select.jsx
components/data-table/__examples__/advanced.jsx
components/data-table/__examples__/fixed-header.jsx
components/tooltip/index.jsx
package-lock.json
package.json
scripts/travis-ci.sh
scripts/upload-diffs.sh
tests/__snapshots__/story-based-tests.snapshot-test.js.snap

Fixes #1743
**All work in these commits was done by @kevinparkerson **
Testing squashed version of #1817 without any snapshot image updates except `DataTable`
Travis has been a pain with the fluid layout data table image snapshots so I added a script to upload image diffs found only on travis to transfer.sh so we can see what it's yelling about. Thanks @cormacmccarthy for the bulk of that work! He created the diff uploader for UVD some time ago and helped me port it over 👍

SLDS update to 2.8.x and store image snapshots when tests fail

---

components/input/private/inner-input.jsx

at line 307 in inner-input.jsx
Fixes #1815
Condition 'props.hasSpinner' is always true at line 307 components/input/private/inner-input.jsx
Thus there is no need to recheck it
---

Condition 'props.hasSpinner' is always true 

---

components/combobox/__examples__/base-custom-menu-item-disabled.jsx
components/combobox/__examples__/base-custom-menu-item.jsx
components/combobox/__examples__/readonly-single-selection-custom-menu-item.jsx
components/combobox/check-props.js
components/combobox/combobox.jsx
components/combobox/private/menu.jsx
components/component-docs.json

Fixes #1707 
Updated `menuItem` prop to `onRenderMenuItem` in such a way that the code base is backward compatible raising following warning in the console in the case using `menuItem` prop.
---

Combobox: Update menuItem to onRenderMenuItem

---

components/button/__docs__/__snapshots__/storybook-stories.storyshot
components/button/__docs__/storybook-stories.jsx

There was a slight spell error in sending the prop to the button.
This commit fixes that and sends the correct name in `assistiveText`.
Fixes #1894
---

Button: Fixes assistive text in small icon hint inverse example

---

components/combobox/__docs__/__snapshots__/storybook-stories.storyshot
components/combobox/combobox.jsx
components/utilities/dialog/index.jsx

Fixes #1818 
@Prophetess Please see if this fixes your issue. I'm thinking this should work due to the order that events fire:
* https://stackoverflow.com/questions/34804719/detect-mousedown-click-event-on-browsers-scrollbar
* https://stackoverflow.com/questions/50895064/handling-blur-click-and-focus-events-of-dropdown-input-suggestion-lists-in-react 
* https://codepen.io/mudassir0909/pen/eIHqB
I'm not seeing the issue in Chrome on my Mac at all and I am able to click the scrollbar in this example http://design-system-react-components.herokuapp.com/?selectedKind=SLDSCombobox&selectedStory=Readonly%20Multiple%20Selection&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel. Are you testing in Windows? What OS and browser are you seeing the scrollbar bug in? …

Combobox: Cancel mouseDown bubble from listbox div tag in order to help scrollbar

---

components/tree/__docs__/__snapshots__/storybook-stories.storyshot
components/tree/private/item.jsx
components/tree/private/render-branch.jsx

Adds `aria-hidden=true` in Tree Buttons and also, edits the assistiveText on the button to align with SLDS
Fixes #1914 
---

Tree Buttons: Adds `aria-hidden=true` to align with SLDS

---

components/menu-dropdown/menu-dropdown.jsx
components/popover/popover.jsx

Deprecate custom content for Dropdown component

---

components/illustration/index.jsx

Fixes #1912
A simple fix for a bug where the illustration component directly manipulates incoming props. Very obscure and not a huge issue unless running in Storybook / dev mode, but worth correcting now since it's simple.
---

illustration component minor bugfix for style object

---

components/component-docs.json
components/modal/__docs__/storybook-stories.jsx
components/modal/index.jsx

Fixes #
1. Updated the Modal Component to fix a "border-radius" style problem when the modal has a footer but not a header. Now only apply the style to the top or bottom corners as appropriate.
2. Added Storybook case "Small no header and custom footer".
---

Modal: Refactor border-radius render logic

---

components/radio-group/index.jsx

Current RadioGroup does not update label props and uses the label set via props in the contrstructor
Fixes #2009
```
/* eslint-disable react/display-name */ import React from 'react';
import PropTypes from 'prop-types';
import { storiesOf } from '@storybook/react';
import { action } from '@storybook/addon-actions';
import RadioGroup from '../../radio-group';
import Radio from '../../radio-group/radio';
import { RADIO_GROUP } from '../../../utilities/constants';
import Base from '../__examples__/base';
class RadioGroupExample extends React.Component {
constructor(props) {
super(props);
this.state = {
labels: {
label: 'Radio Group Label',
},
};
this.onChange = this.onChange.bind(this);
}
onChange(event) {
const { value } = event.target;
this.setState((prevState) => ({
checked: value, …
```

Radio Group: Update labels from props after instance construction

---

components/radio-button-group/index.jsx
components/radio-group/index.jsx

Fixes #2031
@kevinparkerson Merge in #2030 first
RadioGroup and RadioButtonGroup have most of the same code. This issue puts RadioGroup inside of ButtonGroup and integrates RadioButtonGroup render into RadioGroup.
---

Merge Radio Button Group and Radio Group

---

components/popover/__examples__/edit-dialog.jsx
components/popover/edit-dialog.jsx

Fixes #2064 
Looks like I had `SLDSEditDialog/EditDialog` exported in `components/index.js` but I was using a wrong name in the examples. Since it's already exported, I modified the class name to be `EditDialog`. 
---

Fix for: EditDialogPopover is not defined on sites

---

components/button/__tests__/button.browser-test.jsx
components/button/index.jsx
components/component-docs.json
utilities/get-form-props.js

Issue: `<Button formAction='/some/url'>` renders `<button />`
This PR will pass through the `form*` props to `<button formAction='/some/url' />`:
```
'form',
'formAction',
'formEncType',
'formMethod',
'formNoValidate',
'formTarget',
```
---

Button: Pass through form props tom button DOM node

---

components/component-docs.json
components/visual-picker/index.jsx

VisualPicker: Add children prop comment

---

components/component-docs.json
components/index.js
components/welcome-mat/__examples__/default.jsx
components/welcome-mat/__examples__/info-only.jsx
components/welcome-mat/__examples__/steps-complete.jsx
components/welcome-mat/__examples__/trailhead-complete.jsx
components/welcome-mat/__examples__/trailhead.jsx
components/welcome-mat/docs.json
components/welcome-mat/index.jsx
components/welcome-mat/tile.jsx
package.json

Patches up a few overlooked items for welcome mat
* Doc site compatibility
* Icon prop now takes `Icon` component
---

Welcome mat: Doc site compatibility, Icon prop updates

---

components/utilities/UNSAFE_direction/private/language-direction.jsx

Fixes #2108
Use `Consumer` instead of `contextType` to subscribe to context change. I also noticed that `contextType` is only available in 16.6 so we can't use this since we support >= 16.3. 
https://reactjs.org/docs/context.html#classcontexttype
---

Fix for Invalid prop `direction` of value `[object Object]` supplied to `SLDSDialog`, expected one of ["ltr","rtl"]

---

.storybook/preview-head.html
tests/index.html
tests/story-based-tests.snapshot-test.js
tests/storyshots-helpers.js

Fixes #2139
* Currently this is set to divide Storybook `storyKind` by 10 and use those arrays as suites with the same name.
* Adds `getIncludeKindRegex` helper. This was helpful in debugging this issue by adding a subset of stories instead of excluding them.
If passing:
---

Divide Image snapshot tests into chunks

---

components/illustration/check-props.js
components/illustration/docs.json

This is needed since illustration currently does not have a lot of available variants and adding them is tricky.
---

Demoting Illustration component to `prototype` status

---

components/utilities/dialog/index.jsx

Fixes #2182
Added additional context types for dialogs. 
Addressing this issue https://github.com/salesforce/design-system-react/issues/2182

Added additional context types

---

.eslintrc.js
components/checkbox/index.jsx
components/date-picker/private/day.jsx
components/forms/private/label.jsx
components/lookup/lookup.jsx
components/menu-picklist/index.jsx
components/modal/private/manager.jsx
components/progress-bar/index.jsx
components/radio-group/index.jsx
components/slider/index.jsx
components/split-view/__docs__/__snapshots__/storybook-stories.storyshot
components/split-view/__tests__/split-view.listbox.header.browser-test.jsx
components/split-view/listbox.jsx
components/split-view/private/list-item-with-content.jsx
components/textarea/index.jsx
components/tooltip/index.jsx
components/trial-bar/index.jsx
components/utilities/deprecated-warning/index.jsx
components/utilities/label/index.jsx
components/welcome-mat/index.jsx
utilities/sample-data/global-navigation-bar/index.jsx
utilities/sample-data/tree/nodes-base.jsx

Fixes #2184
* Adds `assistiveText` and `labels` strings
* Wraps non-words in `{ }`
---

Prevent literal strings in component source code

---

components/button-group/__docs__/__snapshots__/storybook-stories.storyshot
components/button-group/__examples__/icon-group.jsx
components/button-group/__examples__/list-variant.jsx
components/button-group/index.jsx
components/component-docs.json

Fixes #2153 
Adds label support for all ButtonGroup variants. Also adds a `classNameContainer` prop that applies to the label fieldset container
---

ButtonGroup label support for all variants

---

components/textarea/__docs__/__snapshots__/storybook-stories.storyshot
components/textarea/__docs__/storybook-stories.jsx
components/textarea/__examples__/error.jsx

Making textarea error & required examples match their SLDS counterparts

---

components/component-docs.json
components/radio-button-group/__docs__/__snapshots__/storybook-stories.storyshot
components/radio-button-group/__tests__/radio-button-group.browser-test.jsx
components/radio-group/__docs__/__snapshots__/storybook-stories.storyshot
components/radio-group/__tests__/radio-group.browser-test.jsx
components/radio-group/index.jsx
components/slider/__docs__/__snapshots__/storybook-stories.storyshot
components/slider/index.jsx
components/spinner/__docs__/__snapshots__/storybook-stories.storyshot
components/spinner/__docs__/storybook-stories.jsx
components/spinner/__examples__/default.jsx
components/split-view/__docs__/__snapshots__/storybook-stories.storyshot
components/split-view/listbox.jsx
components/toast/__examples__/duration-toast.jsx
components/toast/index.jsx

Fixes #2336
Corrects the following:
---

More A11y Audit Fixes

---

components/combobox/__docs__/__snapshots__/storybook-stories.storyshot
components/combobox/__examples__/inline-single-search-add-entities.jsx
components/combobox/__examples__/snapshot/inline-single-search-add-entities-open.jsx
components/combobox/combobox.jsx
components/combobox/private/menu.jsx
components/component-docs.json
components/data-table/__docs__/__snapshots__/storybook-stories.storyshot
components/data-table/__examples__/advanced-single-select-fixed-header.jsx
components/data-table/__examples__/advanced-single-select.jsx
components/data-table/__examples__/advanced.jsx
components/data-table/__examples__/fixed-header-horizontal-scrolling.jsx
components/data-table/__examples__/fixed-header.jsx
components/data-table/__examples__/joined-with-page-header.jsx
components/data-table/private/header-cell.jsx
components/data-table/private/row.jsx
components/expression/__examples__/example.jsx
components/expression/__examples__/resource-selected.jsx
components/expression/condition.jsx
components/expression/group.jsx
components/map/index.jsx
components/menu-dropdown/__docs__/__snapshots__/storybook-stories.storyshot
components/menu-dropdown/menu-dropdown.jsx

Accessibility audit fixes for Combobox, DataTable, Expression, Map, and Dropdown

---

components/builder-header/__docs__/__snapshots__/storybook-stories.storyshot
components/color-picker/__docs__/__snapshots__/storybook-stories.storyshot
components/combobox/__docs__/__snapshots__/storybook-stories.storyshot
components/component-docs.json
components/filter/__docs__/__snapshots__/storybook-stories.storyshot
components/global-header/__docs__/__snapshots__/storybook-stories.storyshot
components/panel/__tests__/__snapshots__/filtering.dom-snapshot-test.jsx.snap
components/popover/__docs__/__snapshots__/storybook-stories.storyshot
components/popover/popover.jsx

Fixes #2302
Short, sweet, and simple
---

Popover: Pass aria-haspopup to triggering component

---

components/component-docs.json
components/toast/__docs__/__snapshots__/storybook-stories.storyshot
components/toast/index.jsx

Toast: Focus on dialog container on render instead of close button

---

components/builder-header/__docs__/__snapshots__/storybook-stories.storyshot
components/combobox/__docs__/__snapshots__/storybook-stories.storyshot
components/component-docs.json
components/input/__docs__/__snapshots__/storybook-stories.storyshot
components/menu-dropdown/__docs__/__snapshots__/storybook-stories.storyshot
components/page-header/__docs__/__snapshots__/storybook-stories.storyshot
components/progress-indicator/__docs__/__snapshots__/storybook-stories.storyshot
components/tooltip/__docs__/__snapshots__/storybook-stories.storyshot
components/tooltip/__docs__/storybook-stories.jsx
components/tooltip/__examples__/anchored-nubbin.jsx
components/tooltip/index.jsx

Fixes #2400 & #2401
NOTE: currently the anchored nubbin does not flip with the tooltip... @interactivellama is there a solid way for me to detect when this happens in the current dialog component? If it's unnecessary I might just make `hasStaticAlignment` true when `hasAnchoredNubbin` is true (or recommend that in the comment description)
---

Added onRequestTargetElement and hasAnchoredNubbin prop to tooltip

---

components/tooltip/__docs__/__snapshots__/storybook-stories.storyshot
components/tooltip/index.jsx

Fixes #2423
Small tweak to make `hasAnchoredNubbin` behave reliably when using a controlled `isOpen` Tooltip prop
---

Tooltip `hasAnchoredNubbin` behavior fix

---

components/color-picker/index.jsx
components/combobox/combobox.jsx
components/component-docs.json
components/date-picker/date-picker.jsx
components/lookup/footer.jsx
components/lookup/header.jsx
components/lookup/lookup.jsx
components/lookup/private/item.jsx
components/menu-dropdown/menu-dropdown.jsx
components/menu-picklist/index.jsx
components/notification/index.jsx
components/time-picker/index.jsx
components/tree/__tests__/tree.browser-test.jsx
components/tree/index.jsx
components/utilities/truncate/index.jsx

Fixes #2385
* Moves deprecated components to UNSAFE legacy
* Updates production components
---

Remove componentWillReceiveProps

---

tests/README.md

fix the typo in Unit test Readme

readme typo fix

---

components/component-docs.json
components/filter/__docs__/__snapshots__/storybook-stories.storyshot
components/filter/index.jsx
components/panel/__tests__/__snapshots__/filtering.dom-snapshot-test.jsx.snap
components/panel/filtering/list-heading.jsx

Some minor updates to Filter and Panel markup to bring them up-to-date with the latest from SLDS.
The only visible change is the "x" icon changing into a trash can icon:
Fixes https://github.com/salesforce/design-system-react/issues/2490
@interactivellama Can you please review?  Thanks!

Filter and Panel markup updates

---

components/date-picker/__tests__/date-picker.browser-test.jsx
components/date-picker/date-picker.jsx

Typing in the DatePicker input closes the calendar when it's used as an uncontrolled component.
Fixes https://github.com/salesforce/design-system-react/issues/2489
@interactivellama Can you review when you get a chance? Thanks!

DatePicker: Close calendar when typing in input

---

components/popover/__docs__/__snapshots__/storybook-stories.storyshot
components/popover/__docs__/storybook-stories.jsx
components/popover/__examples__/edit-dialog.jsx
components/popover/edit-dialog.jsx

**Bug Description**
Currently, when passing in disabled="true" to `<EditDialog>`, user can still hover over the pencil icon/ see the color change.
**Expected**
﻿In this case, the pencil icon should not seem clickable while being disabled.
**Fix**
Add `disable` as a prop to `<EditDialog>` and pass it in to its child `<Button>`.
Storybook example added for a disabled `EditDialog` popover
Fixes https://github.com/salesforce/design-system-react/issues/2521
---

Add disable prop to EditDialog and its child Button

---

components/date-picker/private/calendar.jsx

Fixes #
Week start on Datepicker  when IsoWeekDay is true accounts for start of month smaller than start of week.
The datepicker was showing the start of the month without takiing into account IsoWeekDay.
In the example above the 1st should be Sunday but is showing under Monday.
---
* [x ] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [X ] `npm run lint:fix` has been run and linting passes.
* [ X] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [ N/A] Tests have been added for new props to …

Take into account firstDayOfWeekOffset larger than firstDayofMonth on Datepicker

---

package-lock.json
package.json

Reverse fs-extra version bump because we need to update to Node 10+ first.

Reverse fs-extra version bump

---

components/builder-header/index.jsx
components/component-docs.json
components/menu-dropdown/menu-dropdown.jsx
components/popover/edit-dialog.jsx
components/tree/index.jsx
package.json

Fixes #
-  The Edit Dialog now closes when a user clicks outside the component. All of the other popover variations implement this behavior already. This was done by importing from `index.js` (an onClickOutside wrapper for `popover.js` instead of `popover.js` itself. 
- Added documentation for the BuilderHeaderMisc component. It was added in https://github.com/salesforce/design-system-react/pull/2287, but the docs were never updated.
---

Use onClickOutside wrapper for Edit Dialog, add docs for BuilderHeaderMisc

---

components/builder-header/__docs__/__snapshots__/storybook-stories.storyshot
components/builder-header/__docs__/storybook-stories.jsx
components/builder-header/__examples__/custom-icon.jsx
components/builder-header/index.jsx
components/component-docs.json

Add the ability to customize the Builder Header title icon:
Fixes https://github.com/salesforce/design-system-react/issues/2560

Custom title icon for Builder Header

---

components/component-docs.json
components/tabs/__docs__/__snapshots__/storybook-stories.storyshot
components/tabs/__docs__/storybook-stories.jsx
components/tabs/__tests__/tabs.browser-test.jsx
components/tabs/index.jsx
components/tabs/panel.jsx
components/tabs/private/tab.jsx

Add error icon to tab - https://www.lightningdesignsystem.com/components/tabs/#With-Error
---

Tab with error

---

components/color-picker/__docs__/__snapshots__/storybook-stories.storyshot
components/component-docs.json
components/tabs/__docs__/__snapshots__/storybook-stories.storyshot
components/tabs/__docs__/storybook-stories.jsx
components/tabs/__examples__/vertical.jsx
components/tabs/index.jsx
components/tabs/private/tab-panel.jsx
components/tabs/private/tab.jsx
components/tabs/private/tabs-list.jsx

Fixes #
Fixed bug with keydown event with scoped variant not working after the first keydown event.
Added vertical variant with accompanying example and story.
---

Add vertical tab variant

---

components/combobox/__docs__/__snapshots__/storybook-stories.storyshot
components/combobox/combobox.jsx
package-lock.json
package.json
tests/story-based-tests.accessibility-test.config.json

Get accessibility tests running again in Travis CI.  This was a simple fix to avoid setting `NODE_ENV=test` when doing the Storybook static build.
Also: Fix one accessibility test failure.

Get accessibility tests running again

---

components/utilities/truncate/index.jsx

Fixes #1717 
While most modern browsers support Canvas, JSDom does not out-of-the-box. Attempting to run jest jsdom-based tests on code that uses these components results in error messages logged to the console (see #1717).
While it is made clear in the jsdom readme that to support canvas, you need to [add canvas as a peer dependency](https://github.com/jsdom/jsdom#canvas-support), or alternatively [jest-canvas-mock](https://github.com/hustcc/jest-canvas-mock), it seems unnecessary to need to add a dependency just to remove a spurious error message from tests, which doesn't actually affect the running of those tests.
This simple code change in the truncate utility checks that canvas is supported by the environment, with fallback behaviour of not truncating text at all.
---
Please complete …

No mandatory requirement for Canvas

---

components/input/__docs__/__snapshots__/storybook-stories.storyshot
components/input/__docs__/storybook-stories.jsx
components/input/__examples__/inline-help.jsx
components/input/index.jsx
components/input/private/inner-input.jsx

Fixes #2718
- Moves the div for `inlineHelpText` outside of the `InnerInput` div. This makes sure icons are vertically centered (`top: 50%`), because the inline help text no longer affects the input div's height.
- Follows the same pattern as `errorText`, which is rendered outside of `InnerInput` as well
- Added new stories to test these cases
Please take a look, thanks!
---

Fix Input styling with inline help text and icons

---

components/combobox/combobox.jsx
components/expression/__tests__/expression.browser-test.jsx

Fixes #2745
This PR should fix the auto-align issue which affects sub-components like the `date-picker`. The item which is already selected should appear on the bottom of the combo-box view when it's opened.

Fix auto-align of selected item when combo-box is opened

---

components/combobox/__docs__/__snapshots__/storybook-stories.storyshot
components/combobox/__tests__/combobox.browser-test.jsx
components/combobox/combobox.jsx
components/component-docs.json
components/date-picker/__tests__/__snapshots__/datepicker.dom-snapshot-test.jsx.snap
components/expression/__docs__/__snapshots__/storybook-stories.storyshot
components/global-header/__docs__/__snapshots__/storybook-stories.storyshot

Fixes #2753 
According to the Aria 1.2 spec for combobox https://www.w3.org/TR/wai-aria-practices-1.2/examples/combobox/combobox-autocomplete-list.html, the `role="combobox"` attribute should be set on the inner `input` element, not the containing `div`.
---

Combobox: Set role='combobox' on input element

---

components/combobox/__docs__/__snapshots__/storybook-stories.storyshot
components/combobox/__tests__/combobox.browser-test.jsx
components/combobox/combobox.jsx
components/component-docs.json
components/date-picker/__tests__/__snapshots__/datepicker.dom-snapshot-test.jsx.snap
components/expression/__docs__/__snapshots__/storybook-stories.storyshot
components/global-header/__docs__/__snapshots__/storybook-stories.storyshot
tests/axe-config.js

Fixes #2759 
Temporary fix: Added `role="combobox"` to the outer div of the `input` to allow the input to be picked up by the SLDS attribute selectors. See issue description.
---

Combobox: Padding and border issues

---

components/button/__docs__/__snapshots__/storybook-stories.storyshot
components/button/__docs__/storybook-stories.jsx
components/button/__tests__/button.browser-test.jsx
components/button/index.jsx
components/component-docs.json

Adds support for data-* attributes to Button.

---

components/component-docs.json
components/page-header/index.jsx

Adds a note about how the `info` prop can't be used with the `record-home` variant of `<PageHeader />`.
---

Add note about info prop and record-home variant

---

components/card/__docs__/__snapshots__/storybook-stories.storyshot
components/component-docs.json
components/data-table.d.ts
components/data-table/__docs__/__snapshots__/storybook-stories.storyshot
components/data-table/__docs__/storybook-stories.jsx
components/data-table/__examples__/basic-fluid-headless.jsx
components/data-table/component.json
components/data-table/index.jsx
components/data-table/private/head.jsx
components/site-stories.js
package.json

closes #2920
This commit adds a new DataTable prop, `isHeadless: boolean`. Setting
this prop to `true` hides the header by applying
`slds-table_header-hidden` to `table` and `slds-assistive-text` to
`thead`.
---

Add Headless Data Table Support

---

components/component-docs.json
components/data-table/__docs__/__snapshots__/storybook-stories.storyshot
components/data-table/__examples__/joined-with-page-header.jsx
components/data-table/__examples__/resizable-columns.jsx
components/data-table/__tests__/data-table.browser-test.jsx
components/data-table/component.json
components/data-table/index.jsx
components/site-stories.js
package.json

Fixes #2957 and #2960
This also makes the default behavior of column resizing limited to the width of the table instead of overflow:hidden. Scrolling horizontally affects the table container vs column X-axis offset. 
This is what happens after this update: Single columns get smaller and larger without pushing columns to the right and creating a horizontal scroll. Previous column resizing could create a scroll, but scrolling would change the table/column offset here: https://github.com/salesforce/design-system-react/pull/2958/files#diff-80546a80112c877ab129ec5ea2105e98a77c44c98e0be20f51060a011a078ac5R504
---

DataTable: Update resizable options to use `fit`

---

components/combobox/__docs__/__snapshots__/storybook-stories.storyshot
components/combobox/__tests__/combobox.browser-test.jsx
components/combobox/combobox.jsx
components/date-picker/__tests__/__snapshots__/datepicker.dom-snapshot-test.jsx.snap
components/expression/__docs__/__snapshots__/storybook-stories.storyshot
components/global-header/__docs__/__snapshots__/storybook-stories.storyshot
components/portal-settings/__docs__/__snapshots__/storybook-stories.storyshot

This reverts commit 2b249fcae550465f56ef56d6fca683b368ff1d99.
and moves Combobox back to ARIA 1.1 spec
Fixes #2971
---

Revert "Combobox: Set role='combobox' on input element (#2756)"

---

components/combobox/combobox.d.ts
components/combobox/combobox.jsx
components/component-docs.json
components/pill-container/__docs__/__snapshots__/storybook-stories.storyshot
components/pill-container/private/selected-listbox.jsx

This change is to add the ability to show different title of the the multiple selection list. Currently the `title` field is same as the label of the selected option. After that change, user is able to use an optional field `title` in the option, and it will be used  as the `title` property of the selection list
---

add title support for combobox multiple selections

---

components/popover/__tests__/popover.browser-test.jsx
utilities/keyboard-navigable-dialog.js

Fixes #3031 
Verified the updated behavior in a Popover-inside-Modal storybook example (not included in the PR).
---

fix: Popover should stop propagating Escape key event on closing

---

components/modal/index.jsx

Fixes # Deprecation warning in console for `findDOMNode` in StrictMode.
`findDOMNode` is deprecated in StrictMode as it "breaks abstraction levels" and "creates a refactoring hazard" - [React Documentation](https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage). The React documentation instead encourages the use of references. 
This pull request follows this advice and creates a self-reference in the constructor(`selfRef`). This reference is then used in `componentDidUpdate` when it is checked whether the modal is closing. If it is, then instead of using `findDOMNode` to get a reference to the modal and using that for unmounting and removing from the DOM, it instead uses the `selfRef` now.
---

replace usage of findDOMNode with creating selfRef in constructor

---

package-lock.json
package.json

Fixes the following warnings on React 17 and React 18 due to the currently included version of `react-text-truncate` not having up to date peer dependencies.

Upgrade react-text-truncate to latest version

---

components/component-docs.json
components/docked-composer/__docs__/__snapshots__/storybook-stories.storyshot
components/docked-composer/__docs__/storybook-stories.jsx
components/docked-composer/__examples__/base.jsx
components/docked-composer/__examples__/minimized.jsx
components/docked-composer/__tests__/docked-composer.browser-test.jsx
components/docked-composer/component.json
components/docked-composer/index.jsx
components/index.js
components/site-stories.js
utilities/constants.js

Adds [Docked Composer](https://www.lightningdesignsystem.com/components/docked-composer/) to DSR
---

Docked composer

---

components/card/__docs__/__snapshots__/storybook-stories.storyshot
components/card/__docs__/storybook-stories.jsx
components/card/__tests__/card.browser-test.jsx
components/card/index.jsx
components/component-docs.json

Fixes #3068 
Adds functionality to destructured `aria-` and `data-` props on the SLDSCard component.
These props will be destructured on to the root `article` element.
---
**The tests at http://localhost:8001/** have 2 failing (for SLDSComboBox), but it looks like this is also present on the master branch, so not addressed in this PR.

Card component destructure aria data props

---

components/page-header/private/detail-block.jsx

Fixes #3090 
[UI] Shows truncated text in tooltip.
---

Fix Tooltip for PageHeader components

---

components/menu-dropdown/__tests__/dropdown.browser-test.jsx
components/menu-dropdown/menu-dropdown.jsx

Fixes #
Fixes keyboard navigation in menu dropdown component when using the multiple option.
Fixes this issue: Use the keyboard to select an option in the menu dropdown component.  Use the keyboard's up or down arrow keys to advance to the next or previous item. The focus jumps to the first item in the list when pressing the down arrow key or to the last item when pressing the up arrow key.
---

Fix keyboard navigation when using menu dropdown with multiple option

---

package-lock.json
package.json

Salesforce teams are getting TDs to update all UI in MANAGED PACKAGE to have 3:1 color contrast for functional UI elements and 4.5:1 color contrast for text. Example TD (https://gus.lightning.force.com/lightning/r/ADM_Team_Dependency__c/a0nEE000000HnxBYAS/view)
For those apps that use @salesforce-ux/design-system, the newly updated version with wcag compliance is available with `2.21.3-wcag` (https://www.npmjs.com/package/@salesforce-ux/design-system/v/2.21.3-wcag)
I am simply updating the version to the wcag compliant one.

Update design-system to wcag version

---

components/date-picker/private/calendar-wrapper.jsx

fix keyboard trap while pressing tab at today at date-picker now focus goes to previous month
Fixes #
---

@W-16222655 : datepicker_design_system_react fix keyboard trap at today

---

components/component-docs.json
components/date-picker/__tests__/__snapshots__/datepicker.dom-snapshot-test.jsx.snap
package-lock.json
package.json
tests/__mocks__/nanoid-mock.js
tests/story-based-tests.accessibility-test.config.json
tests/story-based-tests.dom-snapshot-test.config.json
tests/story-based-tests.snapshot-test.config.json
utilities/generate-id.js

Copy of #3168. PR created because of CircleCI not checking out latest commits in the branch.
Fixes #3133
---

Add nanoid, remove deprecated shortId
