CONTRIBUTING.md
Updated the add a Storybook URL to https://storybook.js.org/basics/writing-stories/
=> Add a Storybook story URL update

components/avatar/index.jsx, examples/avatar/base.jsx, examples/avatar/entity-icon.jsx, examples/avatar/entity-initials.jsx, examples/avatar/stories.jsx, examples/avatar/user-icon.jsx, examples/avatar/user-initials.jsx, tests/avatar/__snapshots__/avatar.snapshot-test.jsx.snap, tests/avatar/avatar.snapshot-test.jsx
via `testDOMandHTML` helper. Includes some formatting changes w/ linter now working against config.
resolves #1130
=> Add HTML avatar snapshots

examples/modal/header-footer.jsx, examples/modal/menu-contents.jsx, examples/modal/modal-custom-parent-node.jsx, examples/modal/prompt.jsx, examples/modal/sizes.jsx, examples/modal/stories.jsx, examples/modal/taglines.jsx
With new components and design aligned with https://www.lightningdesignsystem.com/components/form-layout/
Fixes #1015.
=> Update modal example

components/notification/check-props.js, components/notification/index.jsx
Partial fix for #1153 and #1154. Alert has been created #1155. Toast will be done soon.
=> Deprecate Notification component

package.json
=> Remove lookup and picklist from doc site

components/combobox/combobox.jsx, components/combobox/private/menu.jsx, examples/combobox/base-custom-menu-item.jsx, examples/combobox/readonly-single-selection-custom-menu-item.jsx, examples/combobox/snapshot/base-custom-menu-item-open.jsx, examples/combobox/snapshot/readonly-single-selection-custom-menu-item.jsx, examples/combobox/stories.jsx, tests/combobox/__snapshots__/combobox.snapshot-test.jsx.snap, tests/combobox/combobox.snapshot-test.jsx
=> Add Combobox custom menuItem Rendering prop

scripts/dist.js
Scripts node version from published packages.
=> Remove node engine version from published package

README.md, docs/webpack.md
Added content to `docs/webpack.md`
Design System React has a peerDependency on [Lightning Design System (LDS)](https://github.com/salesforce-ux/design-system). `Design System React` has kept this as a peer dependency for giving flexibility for developers to choose the different versions of LDS.
If you are planning to use `Design System React` in a standalone application you need to bring in the stylesheets provided by `Lightning Design System (LDS)`.
The classic way to do this is [download](https://www.lightningdesignsystem.com/downloads) the LDS stylesheets and serve it up in your `public` static assets folder and include the stylesheet using
```
<link rel="stylesheet" href="your/public/assets/salesforce-lightning-design-system.min.css">
```
This has a disadvantage of maintaining the …
=> Improve documentation: Usage with webpack #1182

CONTRIBUTING.md, RELEASENOTES.md
Just fixed a couple spelling errors in the markdown documentation.
=> Fix a couple typos

components/lookup/lookup.jsx
=> Add `dialogPosition` prop to Lookup as required for Dialog

components/combobox/combobox.jsx, package.json
Fixes issue #1221
**Functional refactor only**
=> Add lodash.findIndex

components/split-view/index.jsx
The master prop only accepted arrays but should accept element as well. 
---
=> Split View - update master prop to accept array and element.

package.json
Fixes issue #
https://github.com/salesforce/design-system-react/issues/1246
=> Update SLDS peer dependency

components/menu-dropdown/menu-dropdown.jsx
Fix GlobalHeader Profile MenuDropdown issue
Fixes issue #1252
=> Fix GlobalHeader Profile MenuDropdown issue

docs/webpack.md
=> Fix typos in docs/webpack.md

.eslintrc.json, components/forms/checkbox/__docs__/storybook-stories.jsx, components/forms/input/__examples__/icons.jsx, components/notification/__tests__/notification.browser-test.jsx, components/progress-ring/__examples__/examples.jsx, components/progress-ring/index.jsx, components/split-view/__examples__/base-multiple.jsx, components/split-view/__examples__/base.jsx, components/split-view/__examples__/custom-Item-list.jsx, components/split-view/__examples__/external-state.jsx, components/split-view/index.jsx, components/split-view/listbox.jsx, components/split-view/private/list-item-with-content.jsx, components/split-view/private/toggle-button.jsx, scripts/test.sh
Built on #1254.
Last commit is this PR. Merge #1254 before review.
Increases code consistency. Wraps npm ls in travis-ci folding echos to improve CI server UX. 
---
=> Add ESlint rule to never use JSX curly braces when not needed

package.json
=> Updates node engine to 8.x

components/forms/input/index.jsx
=> replaced rendered input block to  code block in docs

CONTRIBUTING.md
=> Clarify new component contribution section

.storybook/addons.js, .storybook/config.js, package-lock.json, package.json
Related to #1180, but #1180 needs automated tests and these are manual warnings that do not end up in the CI. This should help folks contributing.
=> Add a11y panel to storybook

utilities/warning/url-exists.js
Fixes #1388 
Change url-exists to use GET instead of HEAD
---
=> Request icons (console warning) with HTTP GET so webpack dev server doesn't 404

components/component-docs.json, components/global-header/__docs__/storybook-stories.jsx, components/global-header/index.jsx
Fixes https://github.com/salesforce/design-system-react/issues/1416
This changes the GlobalHeader component inline with recent SLDS changes
=> Fix GlobalHeader for latest SLDS

docs/browser-compatibility.md
=> Add Object.assign to list of required polyfills

components/radio-button-group/radio.jsx, components/radio-group/radio.jsx, components/radio/__docs__/site-stories.js, components/radio/__examples__/disabled.jsx, components/site-stories.js
And doc files for doc site
Fixes #1453
---
=> Update Radio component examples

components/menu-dropdown/menu-dropdown.jsx
Fixes #1458
When the dropdown value is being changed in `nextProps`, we are passing in `nextProps.options` along with `nextProps.value`, to handle the case where the options list changes and we are selecting a value within this new options list.
=> Menu Dropdown Value Change

components/index.js
Fixes https://github.com/salesforce/design-system-react/issues/1463
Fixes 
=> Add AppLauncher to CommonJS and ES6 module library export

components/date-picker/date-picker.jsx
=> Datepicker: Increase default years, 5 to 10 years

package-lock.json
Update package-lock.json to latest release (0.8.20)
---
=> Update package-lock.json to latest release (0.8.20)

components/combobox/__examples__/readonly-multiple.jsx, components/combobox/__examples__/readonly-single.jsx, components/combobox/combobox.jsx
Fixes #1484
Fixed #1303
Just comment changes
---
=> Combobox: Clarify prop docs

components/component-docs.json, package-lock.json, package.json
Helps with reading component in #1495
=> Update react-doc-gen version

components/data-table/__examples__/advanced.jsx, components/data-table/__tests__/data-table.browser-test.jsx, components/data-table/check-props.js, components/data-table/index.jsx
Update parameters.
Fixes #1407
---
=> DataTable onChange replaced with onRowChange

CONTRIBUTING.md
@kevinparkerson Does this make the instructions more clear?
**Doc only changes**
=> Clarify adding a new component instructions

components/button/__tests__/button.browser-test.jsx, components/button/index.jsx, components/component-docs.json
Fixes #1529
New prop "style" for Button component
---
=> Button: Add style prop

RELEASENOTES.md
=> Publish 0.8.23 release

scripts/dist.sh
Fixes #1535
This includes `docs.json` for each component which was not being copied.
---
=> Release Build: Copy files not transpiled

components/index.js
=> Add Brand Band export to index

docs/PULL_REQUEST_TEMPLATE.md
Just adding an additional comment to help identify scenario-specific required steps as a reviewer
=> Additional helpful instruction for the pr template

components/combobox/combobox.jsx, components/combobox/index.jsx
=> [IE 11] Do not dismiss combobox lookup menu when clicking on menu scrollbar

RELEASENOTES.md
=> Publish 0.8.26 release

components/tooltip/index.jsx
Fixes #1550
Align learn more variant with SLDS
---
=> Tooltip: Align learn more variant with SLDS

components/data-table/index.jsx
=> Hotfix DataTable stackedHorizontal className.

components/utilities/dialog/index.jsx
Fixes #1571
Looks like I introduced this in the Mocha error fix and made the absolutely positioned dialogs have `right: 0` style always.
---
=> Dialog: Remove isNaN gaurds since ‘inherit’ is not a number

components/vertical-navigation/__tests__/__snapshots__/navigation.snapshot-test.jsx.snap, components/vertical-navigation/index.jsx, components/vertical-navigation/private/item.jsx
Fixes #569
Updates Vertical Navigation markup due to CSS class change.
I also noticed that a shaded Vertical Navigation doesn't exist anymore even though the CSS class does. This is an SLDS issue.
---
=> Vertical Nav: Update SLDS markup/classes

.prettierignore, components/combobox/combobox.jsx, components/date-picker/private/navigation.jsx, components/lookup/__docs__/storybook-stories.jsx, components/lookup/__examples__/default.jsx, components/lookup/__examples__/files.jsx, components/lookup/__examples__/with-selection.jsx, components/menu-dropdown/__docs__/storybook-stories.jsx, components/menu-dropdown/__examples__/checkmark.jsx, components/menu-dropdown/__examples__/custom-trigger.jsx, components/menu-dropdown/__examples__/default-icon-label.jsx, components/menu-dropdown/__examples__/default.jsx, components/menu-dropdown/__examples__/sub-heading.jsx, components/menu-picklist/__docs__/storybook-stories.jsx, components/menu-picklist/__examples__/base.jsx, components/menu-picklist/__examples__/snapshot-default.jsx, components/menu-picklist/__examples__/tooltip-list-item.jsx, components/modal/private/manager.jsx, components/popover/popover.jsx, components/tabs/__docs__/storybook-stories.jsx, components/toast/__tests__/toast.browser-test.jsx, components/utilities/utility-icon/svg.jsx, package.json
Fixes #1596 
Also updates package.json with better CI command for testing to prevent this issue in the future.
---
=> Update prettier CI command

components/brand-band/docs.json, components/button-group/docs.json, components/card/docs.json
As part of #1419, I missed a few components `docs.json`. 
---
=> Adding missing docs.json

components/spinner/__examples__/default.jsx
Fixes #
fix typo in spinner example
---
=> fix typo in spinner example

components/page-header/__docs__/storybook-stories.jsx, components/page-header/private/base/index.jsx, components/page-header/private/detail-block.jsx, components/page-header/private/info.jsx, components/split-view/__tests__/__snapshots__/split-view.snapshot-test.jsx.snap
Fixes #1583
Font size of title details was too big, so the media figure was misaligned. Now there is no need to center the figure for most instances.
http://localhost:9001/?selectedKind=SLDSPageHeader&selectedStory=Base&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
http://localhost:9001/?selectedKind=SLDSPageHeader&selectedStory=Record%20Home%20%28truncates%29&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
AFTER
BEFORE
---
=> Update page header markup

components/component-docs.json, components/data-table/index.jsx
Fixes #917
It appears the warning has already been improved via better default props since this issue was created in March:
If that message is not satisfactory let me know! Otherwise, I followed the brand-band component way of creating a `generatedId` in the constructor, then adding a `getId` function that returns either the passed id prop or generated id when called.
---
=> Data table id bugfixes

components/toast/index.jsx
=> Clear toast duration timeout in componentWillUnmount().

components/tooltip/check-props.js
=> Do not check tooltip isTriggerTabbable if no children.

assets/images/illustrations/empty-state-no-access.svg, assets/images/illustrations/empty-state-not-available-in-lightning.svg, components/component-docs.json, components/illustration/index.jsx
=> Remove <title> from illustrations.

components/combobox/filter.js
Fixes #1625
This is an improvement for the `filter` function of the combobox component. This improves the way `filter` removes already selected options from the options list.
---
=> Combobox filter: Remove selected options based on `option.id` alone.

components/combobox/filter.js
I'm using a Combobox with about 10,000 items in it and there's a noticeable lag in filtering after each keystroke.  After some investigation I discovered that most of the time was being spent in this filter function.  I tested moving the RegExp construction out of the items.filter loop because the constructor carries a pretty heavy performance penalty, and it seems to reduce median filter time for a large list by about 99%.
Before:
After:
---
=> Make combobox filtering more performant by not creating RegExp in a loop

components/combobox/__tests__/__snapshots__/combobox.snapshot-test.jsx.snap, components/combobox/combobox.jsx, components/pill-container/private/selected-listbox.jsx, components/utilities/pill/index.jsx, tests/__snapshots__/story-based-tests.snapshot-test.js.snap, utilities/key-callbacks.js
Fixes #1658
Fixes #1659
Fixes:
* PillContainer/Combobox: All pills should be aria-selected
* Combobox Readonly: Tab key is not propagating
---
=> Combobox/PillContainer: Tab propagation and pill aria selected state

package-lock.json
Maintenance task: This appears to fix #1662
=> Upgrade package-lock.json

components/input/__examples__/counter-input.jsx
Fixes #1665
Fixing a silly issue with input counter examples where more than one node was nested under IconSettings
---
=> Input counter example fix

components/tree/__docs__/storybook-stories.jsx, components/tree/__examples__/default.jsx
=> Tree: Update single select example to expand branch on click

components/index.js
=> Export DataTableHighlightCell in npm module

components/component-docs.json, components/panel/index.jsx
This only adds the className prop, but the Panel could use more things like `dockedLeft`, `isDrawer`, `header`, etc.  I'm open to adding those to this PR, but I'd do that later.
---
=> Adds className prop to Panel.

components/color-picker/__docs__/storybook-stories.jsx, components/color-picker/docs.json, components/color-picker/index.jsx, components/color-picker/private/hsv-color.jsx, components/color-picker/private/swatch-option.jsx, components/color-picker/private/swatch-picker.jsx, components/color-picker/private/swatch.jsx, components/combobox/private/selected-listbox.jsx, package-lock.json, tests/__snapshots__/story-based-tests.snapshot-test.js.snap
Same as PR #1669 but targeting 0.8.x 
Fixes #1627
---
=> 0.8.x color picker accessibility fixes

components/modal/__examples__/menu-contents.jsx
Fixes #
inputs are missing slds in the classes causing the example modals to render improperly
=> add missing slds classes for inputs

.eslintrc.js, CONTRIBUTING.md, components/app-launcher/__docs__/storybook-stories.jsx, components/color-picker/__tests__/color-picker.browser-test.jsx, components/color-picker/index.jsx, components/combobox/__tests__/combobox.browser-test.jsx, components/combobox/combobox.jsx, components/data-table/__tests__/data-table.browser-test.jsx, components/data-table/index.jsx, components/date-picker/date-picker.jsx, components/input/__tests__/input.browser-test.jsx, components/input/index.jsx, components/lookup/lookup.jsx, components/menu-dropdown/__tests__/dropdown.browser-test.jsx, components/menu-dropdown/menu-dropdown.jsx, components/menu-picklist/index.jsx, components/popover/popover.jsx, components/tabs/__docs__/storybook-stories.jsx, docs/codebase-overview.md, package.json, utilities/sample-data/tree/nodes-with-large-dataset.js
* Move bullets into an external and internal section
* Make bullets more scannable with table of contents
* Add file length lint rule of 500 lines
=> Re-organize codebase overview and Add max file line lint rule

components/app-launcher/index.jsx, components/index.js
=> Add AppLauncher Tile and Section to main export

components/combobox/__examples__/base-custom-menu-item.jsx, components/combobox/__examples__/base-inherit-menu-width.jsx, components/combobox/__examples__/base-inline-help-tooltip.jsx, components/combobox/__examples__/base-menu-separator.jsx, components/combobox/__examples__/base-menu-subheader.jsx, components/combobox/__examples__/base-predefined-options-only.jsx, components/combobox/__examples__/base.jsx, components/combobox/__examples__/inline-multiple.jsx, components/combobox/__examples__/inline-single.jsx, components/combobox/__examples__/readonly-multiple.jsx, components/combobox/__examples__/readonly-single-selection-custom-menu-item.jsx, components/combobox/__examples__/readonly-single.jsx, components/combobox/__examples__/required-input-error-state.jsx, package-lock.json, package.json, tests/__snapshots__/story-based-tests.snapshot-test.js.snap
Fixes #1711 
* gives each example a unique id with a random number
@donnieberg @interactivellama 
---
=> [Fix] Combobox ID 

components/menu-dropdown/__docs__/storybook-stories.jsx, components/menu-dropdown/__tests__/dropdown.browser-test.jsx, components/utilities/menu-list/item.jsx, package-lock.json
Fixes # https://github.com/salesforce/design-system-react/issues/1709
---
=> Adds aria-checked and role="menuitemcheckbox" for selectable menus with checkmarks

components/input/index.jsx
new props `styleContainer` to `input`, it passes the style to the outer `div`
---
=> :star2:(input) styleContainer props

components/component-docs.json, components/progress-indicator/index.jsx, components/progress-indicator/private/step.jsx
=> Add ProgressIndicator tooltipPosition option (with sensible defaults).

.github/config.yml
This updates the auto-response to new pull requests with more definition for timing of the review.
=> Define pull request exceptions in more detail

components/brand-band/index.jsx, components/component-docs.json, tests/__snapshots__/story-based-tests.snapshot-test.js.snap
Updating Brand Band documentation to mention potential CSP server setting issues, as well as moving the CSS injection location a level up for better consistency in the current solution
Depending on your server settings, you may get this error due to stye injection.
---
=> Brand Band documentation update

.github/config.yml, components/date-picker/date-picker.jsx
Some questions were asked about MomentJS usage with Datepicker. This change tries to clarify the usage in the documentation.
---
=> Datepicker: Clarify MomentJS usage in props/docs

.github/config.yml
=> Add how to release a tag to 1st time PR bot

components/pill-container/index.jsx
Fixes #1694
---
* [] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
=> Return null if options is empty

components/tooltip/__docs__/storybook-stories.jsx
=> Remove non-breaking text from popover examples

CONTRIBUTING.md, docs/codebase-overview.md
So that contributors benefit from the information 😄 
---
=> Contributing docs: Add new components to package.json

components/accordion/__tests__/accordion.browser-test.jsx, components/app-launcher/__tests__/section.browser-test.jsx, components/app-launcher/__tests__/tile.browser-test.jsx, components/split-view/__tests__/split-view.listbox.header.browser-test.jsx, package-lock.json, package.json
Fixes #1820
Also updates Enzyme and Enzyme DOM queries to work with React >=16.3
---
=> Require React >16.3

components/combobox/__examples__/readonly-multiple.jsx, components/combobox/__examples__/snapshot/base-open-class-name.jsx, components/combobox/__examples__/snapshot/base-open.jsx, components/combobox/__examples__/snapshot/base-selected.jsx, components/combobox/__examples__/snapshot/readonly-multiple-selection-single-item-selected.jsx, components/combobox/__examples__/snapshot/readonly-single-selection-selected-open.jsx, components/combobox/__examples__/snapshot/readonly-single-selection-selected.jsx, components/combobox/__examples__/snapshot/readonly-single-selection.jsx, components/filter/__examples__/assistive-text.jsx, components/filter/__examples__/default.jsx, components/filter/__examples__/error.jsx, components/filter/__examples__/locked.jsx, components/filter/__examples__/new.jsx, components/filter/__examples__/permanant.jsx, components/icon/__tests__/icon.snapshot-test.jsx, components/progress-indicator/__tests__/progress-indicator.browser-test.jsx
=> removed import bindings which are not used

components/button-stateful/index.jsx
=> Used prevState to update state in button-stateful component

components/toast/index.jsx
=> Use role='status' for Toast

docs/create-react-app-2x.md, docs/create-react-app.md
Fixes #
Added documnentation on how to set up Salesforce Lightning Design System with Create React App 2x. Sample repo with everything set up can be found at https://github.com/synle/create-react-app-salesforce-lightning
---
=> added instruction to set up Salesforce Lightning with Create React App 2x

components/button/__docs__/storybook-stories.jsx
Fixes #1919 
Corrects the function called for rendering the button in the example.
---
=> Button: Corrects the function call for text button

components/lookup/__docs__/storybook-stories.jsx, components/utilities/deprecated-warning/index.jsx, utilities/constants.js
Fixes #1921 
Currently, it is not readily visible to the contributors if a component is deprecated or not; they may start to fix an issue with that which would not be necessary if the component is deprecated. This PR adds a utility component for visual deprecation heading to be added to deprecated components. 
---
=> Adds visual deprecation heading to deprecated components

components/progress-ring/__examples__/examples.jsx, components/progress-ring/index.jsx
The docs site examples page was broken due to a wrong export.
This commit fixes the issue by rendering all the modules in a single
module and default exporting that particular module.
Fixes #1887
---
=> Progress Rings: Fixes examples page

components/global-navigation-bar/__docs__/storybook-stories.jsx
=> Removed the overlapping list items in global nav bar

components/app-launcher/section.jsx
The current app launcher sections were having the icons beside
heading that didn't change orientation based on section state.
They basically pointed in the same direction irrespective of the
state of the section. This commit fixes that issue and changes
the orientation of the button icon based on the state of the section.
Fixes #1905
---
=> AppLauncher: Fixes arrow direction in app launcher sections

components/carousel/check-props.js, components/carousel/index.jsx
Carousel is a prototype component but no such warning was being
issued through `check-props`. This commits adds the same.
Fixes #1927 
---
=> Carousel: Adds `isPrototype` warning

components/menu-dropdown/check-props.js
=> Dropdown: Adds sunsetProperty for `tooltip` prop

components/carousel/private/auto-play-button.jsx
=> Fix carousel button import path

components/app-launcher/__docs__/storybook-stories.jsx
A very trivial issue with an equally trivial fix. The fix isn't
particularly necessary for the project but for the sake of
consistency of the elements and the data displayed by elements,
this commit changes the iconText in one of the examples to make
it consistent with the heading.
Fixes #1907
---
=> AppLauncher: Changes icontext in tile to be consistent with heading

components/modal/index.jsx
=> Modal: fix error with dismissModalOnClickOutside

components/date-picker/date-picker.jsx
Adds a `lowPriorityWarning` to the default parser function to
warn the developers against the usage of default parser as it
fails miserably sometimes with internationalization.
Fixes #1507
---
=> DatePicker: Triggers a console warning on using default parser

components/date-picker/date-picker.jsx
Removes the use of `.bind()` and uses arrow functions which is the newer syntax.
---
=> DatePicker: Removes unnecessary bindings and uses arrow functions

components/accordion/__examples__/base.jsx
Fixed a problem with the toggle of the Accordions on some browsers like Firefox.
Tested on Firefox 65.0.1 (Ubuntu 18.04)
Fixes #
---
=> Accordion: Add event parameter in example code

components/popover/__docs__/__snapshots__/storybook-stories.storyshot, components/popover/__examples__/edit-dialog.jsx, components/popover/edit-dialog.jsx
Design updates on #1373 from @kwilloughby-sf 
Update classes and spacing to align with designer audit / red lines.
---
=> Popover: Edit Dialog design updates

components/global-navigation-bar/region.jsx
When tertiary region is used, the component only supports four items at most.
Fixes #
---
=> Global Nav: Add a11y exception to region

components/app-launcher/check-props.js, components/app-launcher/section.jsx, utilities/constants.js
=> Add AppLauncher Section back and deprecate

components/component-docs.json, components/modal/__examples__/sizes.jsx, components/modal/__tests__/modal.browser-test.jsx, components/modal/index.jsx
Fixes #2000 
Added small size support for Modals.
---
=> Add small size support for Modals

docs/codebase-overview.md
Warning about changing default props
=> Codebase: Add default prop change warning

components/builder-header/nav.jsx, components/component-docs.json
@interactivellama just a small typo that I noticed, doesn't need opening an issue IMO.
---
=> Builder Header: Fixes typo

components/checkbox/index.jsx, components/radio/index.jsx
Fixes typo in labels prop of radio and checkbox component, that have crept in with merging of #1786. 
---
=> Fix typo in labels prop of radio and checkbox.

components/site-stories.js
Fixes issue with expandable-section not appearing on site.
---
=> Added expandable-section to site-stories.js

components/component-docs.json, components/date-picker/date-picker.jsx
=> DatePicker: fixed prop description typo

docs/release.md
Adds more notes to release process
---
=> Update release readme

.babelrc
Fixes #2114
“root alias” ~ is used by the doc site only
---
=> Limit use of root `~` babel alias to example files

components/builder-header/__docs__/storybook-stories.jsx, components/builder-header/__examples__/after-successful-save.jsx, components/builder-header/__examples__/base.jsx, components/builder-header/__examples__/failed-save.jsx, components/builder-header/__examples__/successful-save.jsx, components/combobox/__examples__/readonly-multiple.jsx, components/combobox/__examples__/readonly-single.jsx, components/combobox/__examples__/snapshot/readonly-multiple-selection.jsx, components/combobox/__examples__/snapshot/readonly-single-selection-disabled.jsx, components/combobox/__examples__/snapshot/readonly-single-selection-selected.jsx, components/data-table/__examples__/basic-fixed-layout.jsx, components/filter/__examples__/error.jsx, components/icon/__tests__/icon.browser-test.jsx, components/illustration/__docs__/storybook-stories.jsx, components/input/__docs__/storybook-stories.jsx, components/menu-dropdown/__tests__/dropdown.browser-test.jsx, components/popover/__examples__/controlled-with-footer.jsx, components/popover/__examples__/edit-dialog.jsx, components/progress-ring/__examples__/expired.jsx, components/radio/__docs__/storybook-stories.jsx, components/tooltip/__examples__/learn-more.jsx, components/tree/__docs__/storybook-stories.jsx, components/tree/__examples__/default.jsx
Fixes unused imports found with DeepScan in the low priority section.
---
This is more to test a first checkin with a different machine. 
=> Fixing DeepScan issues

components/welcome-mat/__examples__/default.jsx, components/welcome-mat/__examples__/info-only.jsx, components/welcome-mat/__examples__/splash.jsx, components/welcome-mat/__examples__/steps-complete.jsx, components/welcome-mat/__examples__/trailhead-complete.jsx, components/welcome-mat/__examples__/trailhead.jsx
Fixes #2171 
Removed extra " from all Welcome Mats components
---
=> Remove typo error from all mats

components/component-docs.json, components/welcome-mat/__docs__/site-stories.js, components/welcome-mat/__docs__/storybook-stories.jsx, components/welcome-mat/__examples__/default.jsx, components/welcome-mat/__examples__/info-only.jsx, components/welcome-mat/__examples__/splash.jsx, components/welcome-mat/__examples__/steps-complete.jsx, components/welcome-mat/__examples__/trailhead-complete.jsx, components/welcome-mat/__examples__/trailhead.jsx, components/welcome-mat/index.jsx, package-lock.json
Tweaks to welcome mat prior to release
---
=> Welcome Mat release tweaks

components/welcome-mat/__examples__/default.jsx, components/welcome-mat/__examples__/info-only.jsx, components/welcome-mat/__examples__/steps-complete.jsx, components/welcome-mat/__examples__/trailhead-complete.jsx, components/welcome-mat/__examples__/trailhead.jsx
=> Update Icons in Welcome Mat Examples

components/welcome-mat/index.jsx
=> Add Info-Only Class to Welcome Mat Container

components/progress-bar/__docs__/__snapshots__/storybook-stories.storyshot, components/progress-bar/index.jsx, components/setup-assistant/__docs__/__snapshots__/storybook-stories.storyshot
=> Progress Bar: Use `getId` for id instead of hard coding

.eslintrc.js, components/page-header/__docs__/storybook-stories.jsx, components/page-header/__examples__/object-home.jsx, components/page-header/__examples__/record-home.jsx, components/page-header/__examples__/related-list.jsx, components/page-header/__tests__/page-header.browser-test.jsx, components/page-header/private/base/index.jsx, components/page-header/private/object-home/index.jsx, components/page-header/private/record-home/index.jsx, components/page-header/private/related-list/index.jsx, components/split-view/__examples__/base-multiple.jsx, components/split-view/__examples__/base.jsx, components/split-view/__examples__/custom-Item-list.jsx, components/split-view/__examples__/external-state.jsx, components/visual-picker/__tests__/visual-picker.browser-test.jsx, components/welcome-mat/__tests__/welcome-mat.browser-test.jsx, components/welcome-mat/index.jsx
Fixes #2174
Also updates source code to use `React.fragment`
---
=> ESlint: Add React fragment rule

components/tabs/index.jsx
=> Tabs: isTabNode condition fix to prevent clicks from changing Tabs

components/component-docs.json, components/time-picker/__examples__/default.jsx, components/time-picker/index.jsx
Fixes #2261 
Remove default time-picker placeholders to align with the SLDS component
=> Remove default time-picker placeholder text

.travis.yml, package-lock.json, scripts/travis-ci.sh
Testing out Travis build matrixes. Currently accessibility testing takes about 7 minutes. This pull request should break accessibility testing into it's own test suite/VM.
This pull request lowers the CI time from 16 minutes to 11 minutes.
---
=> TravisCI: Enable matrix build

components/component-docs.json, components/expression/__docs__/__snapshots__/storybook-stories.storyshot, components/expression/__examples__/example.jsx, components/expression/formula.jsx, components/expression/group.jsx, components/map/index.jsx, tests/exclude-story-config.js
Fixes #2257
Corrects a11y issues while also making the markup align with SLDS for formula. Also fixes the group trigger menus so that they now work as expected.
---
=> Expression: Fix accessibility bugs

components/component-docs.json, components/map/index.jsx, components/split-view/__docs__/__snapshots__/storybook-stories.storyshot, components/split-view/__examples__/base.jsx, components/split-view/__tests__/split-view.listbox.browser-test.jsx, components/split-view/index.jsx, components/split-view/listbox.jsx
Fixes #2310
@interactivellama not sure there's a way to solve the master width fluctuation problem without explicitly setting the width... but we do have a `masterWidth` property that already has a default of `20rem`, so I think setting both min and max width should be ok. What do you think?
---
=> SplitView: onSelect now called with enter key

package-lock.json, package.json
Reverts salesforce/design-system-react#2312.
Accessibility tests are failing once this code is merged.
=> Revert "Bump @storybook/router from 5.1.9 to 5.1.11"

components/component-docs.json, components/tabs/index.jsx, styles/tabs/tab.css
Fixes #2323
Also updated the custom tabs stylesheet so those now work as expected
---
=> Fixed issue with being able to select "disabled" tabs

components/combobox/__docs__/__snapshots__/storybook-stories.storyshot, components/map/index.jsx, components/progress-ring/__docs__/__snapshots__/storybook-stories.storyshot, components/progress-ring/__examples__/customIcon.jsx, components/progress-ring/__examples__/examples.jsx
=> Add Assistive Text to Icons in Progress Ring Examples

components/combobox/__docs__/__snapshots__/storybook-stories.storyshot, components/map/index.jsx, components/progress-indicator/__docs__/__snapshots__/storybook-stories.storyshot, components/progress-indicator/__docs__/storybook-stories.jsx, components/progress-indicator/private/step.jsx
Fixes #2332
Also adds visual cues to disabled steps
---
=> Progress Indicator now reads "Disabled" for disabled steps

components/button/__docs__/__snapshots__/storybook-stories.storyshot, components/button/__examples__/brand-disabled-destructive-inverse.jsx, package-lock.json
Added margin between button in docs #2338
Fixes #2338
---
=> Add Margin between Buttons in examples

components/accordion/index.jsx
Fixes #2344.
Might also relate to #2339?
---
=> Hotfix Accordion typo

components/combobox/__docs__/__snapshots__/storybook-stories.storyshot, components/combobox/combobox.jsx
=> Combobox: Make Dialog variant work. Update menu down icon style.

components/component-docs.json, components/illustration/check-props.js, components/illustration/component.json, components/site-stories.js, package.json, scripts/prepare-components.js
=> Deprecate and EOL Illustration component

components/accordion/__tests__/accordion.browser-test.jsx, components/accordion/index.jsx
=> Hotfix Accordion to work with one AccordionPanel child.

components/combobox/private/menu.jsx, components/data-table/__docs__/__snapshots__/storybook-stories.storyshot, components/data-table/private/head.jsx
Fixed #2397.
Adds a missing React key and avoid passing an invalid prop type to avoid warnings.
---
=> Fix some React warnings

README.md
=> Add accessibility statement to readme

components/data-table/highlight-cell.jsx
=> Match children prop types as DataTableCell

components/date-picker/__examples__/default.jsx, components/date-picker/__tests__/date-picker.browser-test.jsx, components/date-picker/date-picker.jsx
Fixes #2435
This update remove `componentDidUpdate` completely and makes the use of `value` prop make the component a controlled component and not use internal state. 
---
=> Datepicker: Remove componentDidUpdate

components/combobox/add-subheadings.js
Fixes #2446 
Correctly sorts combobox items by subheader. In the current version, some `accounts` appear in `opportunities`.
---
=> Combobox sort by subheader

.storybook/preview-head.html
Fixes #2186 
The page mentioned in #2186 was showing an MIME type error for the overload.css file so I have added a type to the same tag and to prevent probable future error I also added the same in the link tag above it
---
=> Adding type attribute in the link tag for the CSS stylesheets in storybook

components/combobox/__docs__/__snapshots__/storybook-stories.storyshot, components/combobox/private/menu.jsx, components/component-docs.json, components/spinner/__docs__/__snapshots__/storybook-stories.storyshot, components/spinner/__docs__/storybook-stories.jsx, components/spinner/index.jsx
=> Add inline spinner variant

components/combobox/__docs__/__snapshots__/storybook-stories.storyshot, components/combobox/combobox.jsx, components/pill-container/__docs__/__snapshots__/storybook-stories.storyshot, components/pill-container/private/selected-listbox.jsx, components/popover/__docs__/__snapshots__/storybook-stories.storyshot, components/popover/popover.jsx
Fixes https://github.com/salesforce/design-system-react/issues/2570
---
=> Update markup for combobox/popover/pill-container

CODE_OF_CONDUCT.md, SECURITY.md
Fixes #2629
Adds readmes to comply with global policy.
---
=> Update to Salesforce open source policy

components/component-docs.json, components/data-table/__docs__/__snapshots__/storybook-stories.storyshot, components/data-table/__docs__/storybook-stories.jsx, components/data-table/__examples__/infinite-scrolling.jsx, components/data-table/__tests__/data-table.browser-test.jsx, components/data-table/component.json, components/data-table/index.jsx, components/site-stories.js, package.json
=> Add infinite loading to data table

components/combobox/__tests__/combobox.browser-test.jsx, components/expression/index.jsx, components/files/file.jsx, components/files/index.jsx, components/files/more-files.jsx, components/menu-picklist/index.jsx, components/radio/index.jsx, components/utilities/dialog/index.jsx, components/visual-picker/index.jsx, components/welcome-mat/index.jsx, components/welcome-mat/info-badge.jsx, components/welcome-mat/tile.jsx
=> apply react-codemod rename-unsafe-lifecycles

components/badge/__docs__/__snapshots__/storybook-stories.storyshot, components/badge/__examples__/color-variants.jsx, components/badge/index.jsx, components/component-docs.json
Fixes #2694
The badge component was missing success, warning, and error badge color
options as shown here https://lightningdesignsystem.com/components/badges/#Colors
This commit also fixes a small bug where badges without icons did not
have correct markup due to an empty span still being added when no icon
was provided.
Badge w/out icon before commit
```
<span className="slds-badge">
<span className="slds-badge__icon slds-badge__icon_left" />
423 Credits Available
</span>
```
Badge w/out icon after commit
```
<span className="slds-badge">
423 Credits Available
</span>
```
---
=> update Badge component to support all color variants

components/card/__docs__/__snapshots__/storybook-stories.storyshot, components/data-table/__docs__/__snapshots__/storybook-stories.storyshot, components/data-table/cell.jsx
This brings the `stacked` and `stackedHorizontal` variants/styles of the Data Table component [into line with SLDS](http://www.lightningdesignsystem.com/components/data-tables/#Base) by adding the `data-label` attribute to cells so the table will display the column label next to the cell data value on small viewports as expected.
A simple example:
```
<DataTable 
stacked
items={[
{
id: 'product-1556',
description: 'A humble pineapple',
price: '$14.00',
},
{
id: 'product-123',
description: 'A product so exciting that we could not restrain ourselves and the description ended up being quite long',
price: '$3.95',
},
]}>
<DataTableColumn primaryColumn label="Description" property="description" />
<DataTableColumn label="Your special price" property="price" />
</DataTable>
```
---
Please …
=> Make `DataTableCell` work with "stacked" and "stackedHorizontal"

app.json
=> Remove cedar-14 which is EOL from app.json

package.json
Fixes #2719
Remove NPM version from package.json 
---
=> Remove NPM version from package.json 

components/component-docs.json, components/data-table/__docs__/__snapshots__/storybook-stories.storyshot, components/data-table/__docs__/storybook-stories.jsx, components/data-table/__examples__/advanced-header-row.jsx, components/data-table/cell.jsx, components/data-table/index.jsx, components/data-table/private/row.jsx, package-lock.json
Fixes #2676. Allow custom rendered multi-column headers to be inserted into rows.
---
=> DataTable: Add custom header row

components/combobox/__docs__/__snapshots__/storybook-stories.storyshot, components/combobox/__docs__/storybook-stories.jsx, components/combobox/__examples__/base-with-input.jsx, components/combobox/filter.js, components/combobox/private/menu.jsx
Fixes #2735
When a search term is input to a combobox, the combobox option's `subTitle` is also considered now. Parts of the subTitle that match the search term will also be bold. 
---
=> Filter combobox by subTitle using search term

components/data-table/__examples__/advanced-header-row.jsx, components/data-table/__tests__/data-table.browser-test.jsx, components/data-table/index.jsx
Fixes #2738 
Also fixes the advanced header row example.
=> DataTable: SelectAll issue when header-rows are present

package.json
Fixes #2769
This moves the `webpack-cli` dependency from prod to dev dependencies.
---
=> Move webpack-cli to dev dep.

RELEASENOTES.md, patch.md
Patch release to update package.json move of `webpack-cli`
---
=> Patch release package.json move

package-lock.json
=> Revert package-lock.json to use public NPM (and trigger release)

components/progress-indicator/__docs__/__snapshots__/storybook-stories.storyshot, components/progress-indicator/__tests__/progress-indicator.browser-test.jsx, components/progress-indicator/private/step-vertical.d.ts, components/progress-indicator/private/step-vertical.jsx, components/setup-assistant/__docs__/__snapshots__/storybook-stories.storyshot
Fixes #
Fixes #2766: Vertical Progress Indicator: Added support for onClick event which is documented but doesn't work
---
=> Fixes #2766: Vertical Progress Indicator: Added support for onClick event which is documented but doesn't work

components/component-docs.json, components/data-table/__tests__/data-table.browser-test.jsx, components/data-table/index.jsx
Fixes #2789
This fixes the above issue by simulating a scroll event when the component is updated. This ensures that the data table fetches enough pages to allow the table table to scroll.
---
=> Fix infinite scroll when items are shorter than table height

components/button/__tests__/button.browser-test.jsx, components/combobox/__tests__/combobox.browser-test.jsx, components/component-docs.json, components/data-table/__tests__/data-table.browser-test.jsx, components/expression/index.jsx, components/files/file.jsx, components/files/index.jsx, components/files/more-files.jsx, components/icon-settings/index.jsx, components/input/__tests__/input.browser-test.jsx, components/lookup/__tests__/lookup.browser-test.jsx, components/menu-dropdown/__tests__/dropdown.browser-test.jsx, components/menu-picklist/__tests__/picklist-base.browser-test.jsx, components/menu-picklist/index.jsx, components/notification/__tests__/notification.browser-test.jsx, components/notification/index.jsx, components/radio/index.jsx, components/time-picker/__tests__/time-picker.browser-test.jsx, components/time-picker/index.jsx, components/utilities/dialog/index.jsx, components/visual-picker/index.jsx, components/welcome-mat/index.jsx, components/welcome-mat/info-badge.jsx, components/welcome-mat/tile.jsx
Remove deprecated react lifecycle methods for React 17 upgrade. 
---
=> Remove deprecated react lifecycle methods

.github/dependabot.yml, components/progress-indicator/private/step-vertical.jsx
Buttons were not being rendered with labels from step.
Fixes #2925
---
=> Add missing labels to Progress Indicator

tests/README.md
=> Update to test:dom-snapshot:update

RELEASENOTES.md, patch.md
=> Release: patch

components/menu-dropdown/__docs__/__snapshots__/storybook-stories.storyshot, components/menu-dropdown/__docs__/storybook-stories.jsx, components/menu-dropdown/__examples__/checkmark.jsx, components/menu-dropdown/__tests__/dropdown.browser-test.jsx, components/utilities/menu-list/index.jsx, components/utilities/menu-list/item.jsx
Fixes #2952
Updates examples so that Dropdown button icon is updated when menu item is selected
---
=> Dropdown: Correct checkmark spacing

components/combobox/combobox.d.ts, components/setup-assistant.d.ts
This adds types to the additional event parameters needed for the event props in these components so typescript doesn't fail when type checking. Also a typo fix for the disabled attribute in the options prop type in Combobox.
Fixes #2969
---
=> Fix for typescript types on the Combobox and SetupAssistant component props

components/menu-dropdown/menu-dropdown.jsx
=> Limit menu dropdown opening trigger keys

package.json
https://www.npmjs.com/package/@salesforce-ux/icons
=> Update version of icons

RELEASENOTES.md, patch.md
=> Release patch

eslint-plugin/lib/rules/no-double-dash-modifier.js, eslint-plugin/tests/lib/rules/no-double-dash-modifier.js
fix issues with string template scenarios.
ensure plugin works with modern versions of eslint.
add missing test scenarios.
Fixes #
---
=> fix-eslint-plugin

components/data-table/index.jsx
#2993 introduced a slight regression around propagating table props to cells.
---
=> Datatable: restore prop propagation behaviour

components/slider.d.ts
Fixes #3006 
Updated types to reflect proper signatures.
---
=> Fixed event handler types.

package.json
This allows tools which care about the licensing of the source code here to more
easily deal with this package in validation of licenses.
The license picked here is based on the license for the source code, and the
expectation is that users will consult the README for licenses on other assets.
Fixes #
---
=> package.json: update license to be machine-parsable

components/progress-indicator.d.ts
Fixes #3022 
- Abstracted step and data from event into own types.
- Match event signatures to intended input.
---
=> Type updates/fixes.

components/combobox/combobox.jsx, components/component-docs.json
Fixes #2988
There is a propTypes.txt file that contains a reference to PropTypes.boolean, but I'm unclear how that is generated.
---
=> Fix: Combobox Disabled propType

.circleci/config.yml, package.json
Fixes #3040
This is only a CI change. No library changes. This reverts npm behavior to how it worked in NPM v4-6.
---
=> add --legacy-peer-deps for ci due to npm 7 changes

components/settings.d.ts
=> Fix Typings of component/settings

components/combobox/__docs__/__snapshots__/storybook-stories.storyshot, components/combobox/__docs__/storybook-stories.jsx, components/combobox/__examples__/inline-single-invalid.jsx, components/combobox/__examples__/snapshot/inline-single-invalid.jsx, components/combobox/combobox.jsx, components/combobox/component.json, components/site-stories.js, package.json
Fixes # a CSS error is present in the combobox when variant is inline and an error is present in the box. Img attached having the error and how it looks (with an extra border) and how it should look for reference:
---
=> Combobox single selection - Error Text style fix

preset/package.json.txt
The current value is being flagged by static analysis tools in downstream projects.
Fixes #
---
=> Add license SPDX ID to babel preset

components/docked-composer/__docs__/__snapshots__/storybook-stories.storyshot, components/docked-composer/__examples__/base.jsx, components/docked-composer/__examples__/minimized.jsx, package.json
=> Update Docked Composer doc examples for website

.circleci/config.yml, package-lock.json, package.json
Historically, we have used `npm install` within our CI actions in order to catch dependency breaking changes via the CI--however with the amount of maintenance going on today, this has created issues with testing.
* Removes internal NPM registry from package lock file.
* Update Circle CI to use `npm ci`
---
=> Updates package dependency registry and ci install

README.md
Fixes #
updated readme with new documentation link
=> updated readme with new documentation link

components/combobox/combobox.jsx
Fix added for combobox on enter key pressed same as down key pressed
=> @W-16255012 Fix added for combobox on enter key pressed

package.json
=> bump release
